### ISSUE TITLE
python dict to css / css function

### ISSUE THREAD

**Issue by kor0p** [kor0p/PYX#8]
```python
style=["div", dict(
    display="block",
    color=current_color,
    _=[
        "p", dict(
            color="black",
        ),
    ],
)]
```
or
```python
style=css("div",
    display="block",
    color=current_color,
    _=[css("p", color="black")],
)
```
to
```css
div {
    display: block;
    color: {};
}
div p {
    color: black;
}
```
